name: Generate Sitemap

permissions:
  contents: write

on:
  push:
    paths:
      - '**/*.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install -r requirements.txt || echo "No requirements"

      - run: python generate_sitemap.py

      - name: Commit and push sitemap
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.html sitemap.xml
          git commit -m "Auto-update sitemap [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
